services:
  rag-app:
    build: .
    container_name: docker-rag-app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    networks:
      - rag-network

  streamlit-frontend:
    build: .
    container_name: docker-rag-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    command: ["streamlit", "run", "src/frontend/streamlit_app.py", "--server.address", "0.0.0.0", "--server.port", "8501"]
    depends_on:
      - rag-app
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge