version: '3.8'

services:
  rag-api:
    build: .
    container_name: rag-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./resources:/app/resources
    environment:
      - ENVIRONMENT=development
      - VECTOR_DB_TYPE=local
      - LLM_PROVIDER=openai
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - vector-db

  vector-db:
    image: qdrant/qdrant:latest
    container_name: rag-vector-db
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334

  nginx:
    image: nginx:alpine
    container_name: rag-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rag-api

volumes:
  qdrant_storage: