version: '3.8'

services:
  rag-app:
    build: .
    container_name: docker-rag-app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge